services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql_server_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Kwameldx666"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: